genome-nexus/genome-nexus-frontend

- src/component/QueryExamples.tsx
- src/page/Main.tsx
1. update links
2. remove the blank gap between footer and query example table
> update query example

- package.json
- src/component/GenomeNexusMutationMapper.tsx
- src/page/Variant.tsx
- yarn.lock
hide y-axis and track selector, set lollipop and plot height
fix https://github.com/cBioPortal/cbioportal/issues/6618
merge https://github.com/cBioPortal/react-mutation-mapper/pull/94 first
> mutation mapper standalone fixes

- pom.xml
This allows us to include the frontend as a dependency in Java projects.
> Add pom file for compilation on jitpack

- src/component/variantPage/TranscriptSummaryTable.tsx
- src/page/Variant.tsx
- src/util/AnnotationSummaryUtil.ts
fix transcript table when missing fields
for example: 10:g.32361324_32361325delinsCT
TODO: add some tests https://github.com/genome-nexus/genome-nexus-frontend/issues/23
> Transcript table fix

- src/component/GenomeNexusLogo.tsx
- src/component/Header.css
- src/component/Header.tsx
fix:
https://github.com/genome-nexus/genome-nexus-frontend/issues/25
https://github.com/genome-nexus/genome-nexus-frontend/issues/28
https://github.com/genome-nexus/genome-nexus-frontend/issues/29
> Header improvement

- src/page/Variant.tsx
- src/page/genomeNexusClientInstance.ts
Keep using https://www.genomenexus.org when running on netlify or in
development mode.
> Make apiRoot work when included in backend project

- src/component/SearchBox.css
- src/component/SearchBox.tsx
- src/page/Home.css
- src/page/Home.tsx
- search bar in center of page
- auto focus on search bar
- add search icon
- left align cursor
fix https://github.com/genome-nexus/genome-nexus/issues/334
> search box enhancements

- README.md
- package.json
- src/component/variantPage/BiologicalFunction.tsx
- src/component/variantPage/FunctionalGroups.tsx
- src/component/variantPage/FunctionalPrediction.tsx
- src/component/variantPage/TherapeuticImplication.module.scss
- src/component/variantPage/TherapeuticImplication.tsx
- src/component/variantPage/biologicalFunction/BiologicalFunction.module.scss
- src/component/variantPage/biologicalFunction/Oncokb.tsx
- src/component/variantPage/functionalGroups.module.scss
- src/page/OncokbClientInstance.ts
- src/page/Variant.tsx
- src/page/VariantStore.ts
- yarn.lock
try 
7:g.55249071C>T (sensitive and resistant)
1:g.115256529T>C (long name)
17:g.41226411G>A (sensitive with multi levels)
> Add OncoKB

- src/component/Footer.tsx
- src/component/Header.tsx
- src/page/Home.css
- src/page/Home.tsx
Add link to API and documentation
> change header+footer+description

- src/component/Header.tsx
- src/page/Home.tsx
Was just changing url route but not actually doing a server request for the API page
> fix header link 🔧

- src/component/variantPage/BasicInfo.module.scss
- src/component/variantPage/BasicInfo.tsx
- src/component/variantPage/PopulationPrevalence.tsx
- src/component/variantPage/TherapeuticImplication.tsx
- src/component/variantPage/biologicalFunction/BiologicalFunction.module.scss
- src/component/variantPage/biologicalFunction/Oncokb.tsx
- src/component/variantPage/functionalGroups.module.scss
- src/component/variantPage/functionalPrediction/MutationAssesor.tsx
- src/component/variantPage/functionalPrediction/PolyPhen2.tsx
- src/component/variantPage/functionalPrediction/Sift.tsx
- src/component/variantPage/functionalPrediction/styles/annotation.module.scss
- src/page/Variant.tsx
- everything clickable
- point oncokb link to alteration page
- sources style changes
> make data clickable

- src/component/Footer.tsx
should reload and go to swagger page
fix https://github.com/genome-nexus/genome-nexus/issues/359
> fix api link

- src/page/Home.tsx
trim the query input and remove whitespace in example
> trim the query input

- src/component/Footer.tsx
- src/component/Header.tsx
- src/component/SearchBox.tsx
- src/page/Home.tsx
- change first example because of missing PTM
- add tools and github to the header
- add github icon to footer
fix https://github.com/genome-nexus/genome-nexus/issues/367
> change example, update header and footer

- .circleci/config.yml
- .gitignore
- netlify.toml
- package.json
- pom.xml
- src/App.tsx
- src/component/variantPage/BasicInfo.tsx
- src/component/variantPage/BiologicalFunction.tsx
- src/component/variantPage/FunctionalGroups.tsx
- src/component/variantPage/FunctionalPrediction.tsx
- src/component/variantPage/TherapeuticImplication.tsx
- src/component/variantPage/biologicalFunction/Oncokb.tsx
- src/component/variantPage/functionalPrediction/MutationAssesor.tsx
- src/page/OncokbClientInstance.ts
- src/page/Variant.tsx
- src/page/VariantStore.ts
- yarn.lock
- Getting oncokb data by using cbioportal proxy. 
- update cbioportal frontend commons and react mutation mapper
https://github.com/genome-nexus/genome-nexus/issues/17
> Getting oncokb data by using cbioportal proxy

- src/component/SearchBox.tsx
related to: https://github.com/genome-nexus/genome-nexus/issues/382
> indicate hg19 support only

- src/page/Home.tsx
- src/page/Variant.tsx
- src/page/VariantStore.ts
Fix:https://github.com/genome-nexus/genome-nexus/issues/417
- fix error when annotation failed
example:
https://deploy-preview-77--genome-nexus-frontend.netlify.app/variant/10:g.41242960_41242963insGA
> fix blank page when annotation failed

- src/component/variantPage/BasicInfo.tsx
- src/component/variantPage/FunctionalPrediction.tsx
- src/config/configDefaults.ts
- src/page/VariantStore.ts
add `SHOW_MUTATION_ASSESSOR` to config file, and set it to `true`
> add mutation assessor back on GN frontend

- src/component/SearchBox.tsx
- src/page/Home.tsx
Fix: https://github.com/genome-nexus/genome-nexus/issues/505
> update search box examples

- src/page/VariantStore.ts
Fix genome-nexus/genome-nexus#512
> Enable OncoKB

- src/component/variantPage/biologicalFunction/ClinvarInterpretation.tsx
- Add linkout icon to clinvar
- Update clinvar description in tooltip
> add linkout icon to clinvar

- .circleci/config.yml
- netlify.toml
- package.json
- yarn.lock
Fix genome-nexus/genome-nexus#528
> Update node version to 15.2.1 and yarn version to 1.22.5

- src/component/SearchBox.tsx
- src/config/configDefaults.ts
- src/page/Home.tsx
- src/page/VariantStore.ts
- src/util/SearchUtils.ts
- src/util/variantValidator.tsx
Fix: https://github.com/genome-nexus/genome-nexus/issues/312
> Search box update

- src/component/variantPage/TranscriptSummaryTable.tsx
- src/page/Variant.tsx
- src/page/VariantStore.ts
- src/util/AnnotationSummaryUtil.ts
- src/util/variantUtils.ts
Fix: https://github.com/genome-nexus/genome-nexus/issues/513
Should update protein change when switching transcripts
> update lollipop when switch transcript

- src/component/variantPage/ClinicalImplication.tsx
- src/component/variantPage/clinicalImplication/Civic.tsx
Add star to civic when switching to a non canonical transcript.
> add star to civic when switching to a non canonical transcript

- src/component/variantPage/functionalPrediction/MutationAssesor.tsx
- src/component/variantPage/functionalPrediction/styles/mutationAssessorTooltip.module.scss
Related to genome-nexus/genome-nexus#534
> Make mutation assessor section expandable

- src/component/variantPage/functionalPrediction/Sift.tsx
- src/component/variantPage/functionalPrediction/styles/siftTooltip.module.scss
Related to genome-nexus/genome-nexus#534
> Make sift section expandable

- src/component/variantPage/clinicalImplication/EvidenceSummary.tsx
Fix genome-nexus/genome-nexus#544
> Fix evidence table width

- .env
- src/component/SearchBox.tsx
- src/component/ValidatorNotification.tsx
- src/page/Home.tsx
- src/util/SearchUtils.ts
Part of: https://github.com/genome-nexus/genome-nexus/issues/540
Search genome nexus index db first, if click "Show more", then search from recoder.
> Support search internal index db

- .prettierignore
- package.json
- src/component/Header.tsx
- src/doc/News.md
- src/page/Main.tsx
- src/page/News.scss
- src/page/News.tsx
- yarn.lock
Fix: https://github.com/genome-nexus/genome-nexus/issues/568
> Add news page

- src/page/Home.tsx
- src/page/VariantStore.ts
- Add validation back, it’s still good to have it because every variants we search will be stored into database, so I believe it’s good to eliminate number of wrong formats variants in db.
> Add variants validation back

- src/component/SearchBox.tsx
- src/component/variantPage/biologicalFunction/Oncokb.tsx
- src/doc/News.md
- src/page/Home.tsx
- src/util/SearchUtils.ts
> Home page and grch38 updates

- src/component/SearchBox.tsx
- src/page/Home.tsx
- src/util/SearchUtils.ts
Our frontend code doesn't support grch38 search well
> Grch38 search function

- src/component/Header.css
- src/component/Header.tsx
- src/component/SearchBox.tsx
- src/component/shared/WindowStore.ts
- src/component/variantPage/functionalGroups.module.scss
- src/page/Home.scss
- src/page/Home.tsx
- src/page/News.scss
- src/page/News.tsx
- src/page/Variant.tsx
Fix some small screen (especially on phone) responsive issues.
> Fix small screen responsive issues

- src/component/variantPage/FunctionalGroups.tsx
- src/component/variantPage/FunctionalPrediction.tsx
- src/component/variantPage/functionalPrediction/MutationAssesor.tsx
- src/config/configDefaults.ts
- src/page/Variant.tsx
- src/page/VariantStore.ts
Part of: https://github.com/genome-nexus/genome-nexus/issues/634
Test: https://deploy-preview-138--genome-nexus-frontend.netlify.app/variant/17:g.7577121G%3EA
> Enable Mutation Assessor and remove unavailable fields

- src/component/SearchBox.tsx
- src/page/Home.scss
- src/page/Home.tsx
Make some style tweaks on home page and hopefully attract more citations.
> Add citation info on home page

- src/doc/News.md
> Update news for 2022
